### ISSUE TITLE
Is node.js strictly necessary?

### ISSUE THREAD

**Issue by samaaron** [SunderB/sonic-pi-phoenix-website#1]
With Phoenix 1.6 webpack and node are no longer necessary. Instead you can use esbuild to build js assets. I really think we should be using that as it's waaaay simpler to work with :-)

https://www.phoenixframework.org/blog/phoenix-1.6-released

**Comment by ethancrawford** [comment]
Correct. I noticed the option of esbuild previously but by that time had stopped doing any more work on my P.O.C. until further development discussion could take place. Totally agree with getting rid of webpack/node!

**Comment by ethancrawford** [comment]
(@SunderB - FWIW, my P.O.C. was not necessarily using the best Elixir or Phoenix code - I barely knew either when I first built the thing... I just hacked something together that worked enough to demonstrate the basic idea 😅 )

**Comment by SunderB** [comment]
> 
> 
> (@SunderB - FWIW, my P.O.C. was not necessarily using the best Elixir or Phoenix code - I barely knew either when I first built the thing... I just hacked something together that worked enough to demonstrate the basic idea 😅 )

That's fine :P I just copied the P.O.C as a starting point, we can refactor it if needed

**Comment by SunderB** [comment]
Should be sorted in 03e1079 :)
