### ISSUE TITLE
Discuss js/css deps

### ISSUE THREAD

**Issue by samaaron** [SunderB/sonic-pi-phoenix-website#15]
Hi there,

its' great to see activity here - I think that moving the website inside of Sonic Pi will be a really nice move.

I've also been working a lot in this area a lot and have some thoughts about how to move forward that I'd like to discuss as I think there might be some conflicts and I want to reduce unnecessary work as much as possible.

Firstly, I want us to move away from using npm and webpacker. These things are really complex and have been tricky for me to install myself and I really don't want to have to support others using it. Instead, Phoenix is moving towards using esbuild and I've been having a lot of success with it. 

I've also been experimenting with the Petal stack and this feels like an excellent direction to go. I've got a local setup working which supports live reloading, rebuilding css, js, etc and works out of the box with our existing build infrastructure with no extra steps necessary. It's highly based around this: https://github.com/petalframework/petal_boilerplate

I'll be merging my work with the `dev` branch at some point, so hopefully that will make it easier for us to work with the same tools and approach. But before then, I'm really interested in your thoughts about this and particularly if you have any major objection to this direction.

**Comment by ethancrawford** [comment]
I had already assumed ditching npm and webpacker was the direction we were heading in 🙂 this all sounds ok to me 👍

**Comment by ethancrawford** [comment]
Apologies, but having had a better look at Petal, I do have one or two hesitations about it.
Maybe not showstoppers, but bootstrap for example appears to be a much more mature framework. It has some very useful components that we could use, that Petal appears to be currently lacking: button groups, the accordion, the offcanvas, and perhaps most practically helpful, unless I'm not seeing it, flexible responsive grid layout options (for working with columns and/or rows. Petal does have 'containers', just like bootstrap, but it might a bit more work to change their layout direction than it would be with bootstrap. I wouldn't know for sure, as I've never used it or tailwind before).

Also, bootstrap is designed to be easily customised, and is more than just a component library - having utilities, an easily extendible API, etc - and is always free. With Petal, you only get the component library (and a basic boilerplate) in the free version. To get access to utility functions (amongst other things we may not need) you need to pay $299 USD (and the same again every year if you want continuous support and updates).

No doubt it would be possible to create the missing components with some custom html/css/javascript - but it would mean more work. I'm fairly well familiar with bootstrap, so if you want to go with Petal instead, it may mean more delays as we/I familiarise ourselves/myself with Petal and build in any missing components that we feel are important to add. @SunderB - your thoughts?

**Comment by ethancrawford** [comment]
(In short, my preference would probably be to stay with something more mature and flexible like bootstrap, but I'm happy to discuss this more)

**Comment by ethancrawford** [comment]
The tailwind project by itself looks fairly similar to bootstrap, inasmuch as it provides both a responsive, mobile-first CSS framework and a component library. The tailwind component library does _not_ have a free option, but unlike Petal, a once off purchase includes lifetime free updates. Its component library is also a lot more comprehensive.

**Comment by samaaron** [comment]
I'm open to discussion and appreciate the points about the benefits of familiarity. However, I'm really strongly against npm or webpack. Is it possible to use bootstrap as a stand-alone js/css dep without any need for extra tooling?

Also, I'm definitely not advocating the need for buying any software/components. I'm just thinking that tailwind and alpinejs feel like solid choices going forward and integrate very nicely with our current build process.

**Comment by samaaron** [comment]
Also, with respect to the existing website, it currently doesn't need any fancy js/css frameworks, so should be possible to port to Phoenix as is with minimal changes - the only complexity I saw was using templates to plug in the different translations. Of course, if there's an opportunity to improve things then I'm all up for that - but not at the cost of increased complexity.

**Comment by ethancrawford** [comment]
> Is it possible to use bootstrap as a stand-alone js/css dep without any need for extra tooling?

See here: https://getbootstrap.com/docs/5.1/getting-started/download/#compiled-css-and-js

> tailwind and alpinejs feel like solid choices going forward

I have no real problem with tailwind or alpinejs per se (particularly since as I mentioned above tailwind is a responsive  mobile first framework). The limited and seemingly less flexible Petal component library is the part that seems less desirable to me, in spite of its free availability.

I think I'll wait until someone else can join the conversation before adding any more comments 🙂

**Comment by samaaron** [comment]
Petal just stands for Phoenix, esbuild, Tailwind, Alpine and Live View. That's all I'm suggesting. The boiler plate project I was linking to above was just a nice way of packaging all these things together in a way that's harmonious to our current build process.

**Comment by SunderB** [comment]
Hey :)
As far as I'm aware, we're already using esbuild to package dependencies. I've also had issues with using npm with the project (e.g. getting bootstrap's js components to work), so I'd be happy to move to something simpler (e.g. put bootstrap in the static_assets, and just include it on the webpage).

**Comment by SunderB** [comment]
I've never used Tailwind CSS before, but it seems interesting. From what I've read it's similar to Bootstrap? AlpineJS seems nice and simplistic, but I don't currently know how it would be beneficial or what it could do that plain JS can't?

If we're going for simplicity, I think sticking to plain JS and Phoenix Live View where possible whilst possibly using something like Bootstrap or Tailwind CSS to help with layout/styling would be a good idea.

Also, I'd stay well away from needing any tools that cost money, at all costs!

**Comment by samaaron** [comment]
@SunderB cool - I'm definitely down for plain js and Live View. I think having a default js/css toolset could also be useful too, which I guess is all I'm proposing here. Definitely not considering anything that's not MIT licensed (or roughly equivalent).

**Comment by ethancrawford** [comment]
> I think having a default js/css toolset could also be useful too

Yes, agreed. Like I said above - Tailwind is definitely interesting, and seems fairly equivalent to bootstrap, at least in terms of things such as flexibility, mobile-first design, accessibility, customisation ability, etc. Petal as a framework seems nice too, and would definitely fit in with our current build process as you say. It just seems a little under-developed to me so far, given the lack of availability of a reasonably comprehensive library of free components. I guess I'd much rather not have to reinvent the wheel when it came to building UI components, but neither would I want to just avoid using some kind of UI components altogether - so if the choice was Petal components or complete DIY, I'd (probably) choose Petal 🙂 

Re javascript, I have no strong preference either way. If part of the point of tailwind (just like bootstrap) is to minimise the need for javascript in UI components, then there may be less need for custom javascript frameworks. (If little bits of plain javascript are enough to make things work, it saves us and contributors from the community having to learn another tool).

**Comment by ethancrawford** [comment]
Do we close this now that you have committed to the Petal stack @samaaron ?

**Comment by samaaron** [comment]
Nothing is set in stone - but I feel strongly we should unify around a core set of web tech and tailwind + alpine definitely feels like a strong direction. Rails has been strongly moving towards tailwind and alpine was specifically designed for the LiveView model. As I said before, I also want to avoid npm (which also seems to be the general trend).

**Comment by samaaron** [comment]
I'll close it for now. Let's see if we can work on top of petal going forward and if there are serious issues, let's open another issue and discuss :-)

**Comment by samaaron** [comment]
BTW, it should now be possible to do development work *within* Sonic Pi itself. You just need to add a new config file `~/.sonic-pi/config/tau-settings.toml`. Inside there you can use the following keys:

```
env = "dev"
phx_port = 8888
```

This will then ensure the BEAM process starts in dev mode using `mix`. It will also force the webserver to run on port 8888. If you get into a position where you need to restart the BEAM, you can just hit `F8` in Sonic Pi and it will be restarted automatically. Live code reloading (Erlang/Elixir) + live asset rebuilding (js/css) should also happen automatically on file save. I think it's going to be a really nice development experience.

**Comment by SunderB** [comment]
@samaaron should development continue in this repo for now or should we move to the sonic pi repo? I feel having a separate repo would be good until we've got a solid base.

**Comment by samaaron** [comment]
Hey @SunderB - agreed that a separate repo makes sense for now during this experimental exploratory phase. However, it probably makes sense to look to merge things at this stage. This could be by forking Sonic Pi itself and mapping this work into the existing directory structures or finding some way to symlink this work into an existing clone.

**Comment by ethancrawford** [comment]
@samaaron keeping it in a separate repo but still merging current work? not sure I follow...
