### ISSUE TITLE
Functions with special characters in them need more appropriate handling

### ISSUE THREAD

**Issue by ethancrawford** [SunderB/sonic-pi-phoenix-website#17]
Currently, some of the TOML files have names that are incompatible with Windows, causing developing on Windows to be very difficult. This needs to be changed.
Renaming the files themselves is half the solution. The Lang docs also use the filename to print out the name of the lang function on the documentation pages as well, which makes things a little more involved. We don't want characters like `?` in the filenames, but we _do_ want them in the titles on the documentation pages.

Introducing something like `title = "name_with_a_?"` (eg `title = "block_slept?"` into the lang TOML files allows us to have the proper function names listed in the sidebar navigation. However, the top level table key in the lang TOML files are still used to generate the list of `activepages`, which does not help when creating the page URLS. (Ie, in the TOML file for `block_slept?`, the top level table key of `["block_slept?"]` is fine for internal purposes but it should not directly generate the page URL. (We don't want the `?` included in the URL, even if it is URL encoded). This too needs updating somehow.

**Comment by SunderB** [comment]
Ah, I didn’t realise question marks don’t work on windows.
Maybe something like this could work:
In the toml generator:
* Replace any ? in file names with an _
* Add the title key

In the loader:
* Modify it to use the actual file name for the url

**Comment by ethancrawford** [comment]
Not sure yet which way feels better, to replace with `_`, or just leave off the end character entirely - but sure, we can go with `_` for now. It can always be changed later 😉

**Comment by SunderB** [comment]
Cool 🙂 I was thinking just in case there’s ever two similar functions like `block_slept` and `block_slept?`

**Comment by ethancrawford** [comment]
Great point!
